version: '2'

services:
    db:
        image: mongo
        container_name: mongodb
        networks:
            - app-network
    api:
        container_name: nodeapp
        build:
            context: .
            dockerfile: ApiNodeDockerfile
        ports:
            - "3000:3000"
        networks:
            - app-network
        depends_on: 
            - db
    push-notification-server:
        container_name: pushNotificationServer
        build:
            context: .
            dockerfile: PushNotificationNodeDockerfile
        ports:
            - "8080:8080"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge